deployments:
  environmentMapping:
    development:
      - "dev*"
      - "deploy"
      - "PSPA-*"
    testing:
      - "test*"
    staging:
      - "staging*"
    production:
      - "production*"
      
